name: Blogger Auto Poster

on:
  workflow_dispatch: # Memungkinkan trigger manual dari tab Actions di GitHub
  schedule:
    # Mengambil interval dari state.json akan rumit.
    # Cara termudah adalah menjalankannya setiap jam dan membiarkan skrip memutuskan.
    # Cron ini berjalan setiap jam, pada menit ke-0.
    - cron: '0 * * * *'

permissions:
  contents: write # Memberi izin pada Action untuk menulis kembali ke repo (update state.json)

jobs:
  post-to-blogger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run posting script
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: node src/main.js

      - name: Commit and push state file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add state.json
          # Hanya commit jika ada perubahan pada state.json
          git diff --quiet --exit-code state.json || git commit -m "Update posting state"
          git push
