name: Blogger Auto Poster

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write

jobs:
  post-to-blogger:
    runs-on: ubuntu-latest
    
    # --- TAMBAHKAN BARIS INI ---
    env:
      TZ: 'Asia/Jakarta' 
    # --------------------------

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run posting script
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: node src/main.js

      - name: Commit and push state file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add state.json
          git diff --quiet --exit-code state.json || git commit -m "Update posting state"
          git push
